image: ubuntu:latest

before_script:
  - apt-get update -qq && apt-get upgrade -y
  - apt-get install -y gcc g++ cmake make
  - apt-get install -y python3-dev python3-venv

stages:
  - build
  - release

build-debug:
  stage: build
  only:
    - development
    - TestCI
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /WIP/
  script:
    - make debug
    - make test

build-release:
  stage: release
  tags:
    - setup
  only: 
    - master
    - TestCI
  script:
    - make install
    - make test
