image: ubuntu:latest

stages:
   - test

before_script:
   - export DEBIAN_FRONTEND=noninteractive
   - apt-get update -qq && apt-get upgrade -y
   - apt-get install -y gcc g++ cmake make git
   - apt-get install -y python3-dev python3-venv
   - apt-get install -y libopenmpi-dev libhdf5-openmpi-dev
   - apt-get install -y freeglut3-dev

test:debug:
   stage: test
   only:
      - development
      - master
      - TestCI
   tags:
      - docker
   except:
      variables:
         - $CI_COMMIT_MESSAGE =~ /WIP/
   script:
      - make BUILD=debug install
      - make test
      - make examples/requirements
      - for f in examples/*.py; do echo "$f"; env/bin/python3 $f; done

# TODO: test-mpi 
# - export HDF5_DIR="/usr/lib/x86_64-linux-gnu/hdf5/openmpi"

test:release:
   stage: test
   only: 
      - development
      - master
      - TestCI
   tags:
      - docker
   except:
      variables:
         - $CI_COMMIT_MESSAGE =~ /WIP/
   script:
      - make BUILD=release install
      - make test
      - make examples/requirements
      - make docs
      - for f in examples/*.py; do echo "$f"; env/bin/python3 $f; done
