image: ubuntu:latest

before_script:
  - apt-get update -qq && apt-get upgrade -y
  - apt-get install -y gcc g++ cmake make git
  - apt-get install -y python3-dev python3-venv
  - apt-get install -y libopenmpi-dev freeglut3-dev libhdf5-openmpi-dev

stages:
  - debug
  - release

build-debug:
  stage: debug
  only:
    - development
    - TestCI
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /WIP/
  script:
    - export HDF5_DIR="/usr/lib/x86_64-linux-gnu/hdf5/openmpi"
    - make git-submodules
    - make BUILD=debug install
    - make BUILD=debug test

build-release:
  stage: release
  only: 
    - master
    - TestCI
  script:
    - export HDF5_DIR="/usr/lib/x86_64-linux-gnu/hdf5/openmpi"
    - make git-submodules
    - make BUILD=release install
    - make BUILD=release test
