fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ["-i", "--style=file"]
      - id: cppcheck
        args:
          [
            --std=c++20,
            --language=c++,
            --inline-suppr,
            --check-config,
            --error-exitcode=1,
            --enable=all,
            --suppress=unmatchedSuppression,
            --suppress=missingIncludeSystem,
            --suppress=unusedFunction,
          ]
      - id: cpplint
        args:
          [
            "--filter=-whitespace,-whitespace/indent,-whitespace/comments,-readability/todo,-build/c++11,-build/include_order,-legal/copyright,-runtime/references",
            "--header=cuh,h,h++,hh,hpp,hxx,inl,tpp",
          ]
      # takes a long time. local better use "run-clang-tidy -p build src/**/* include/**/*"
      # - id: clang-tidy
      #   args:
      #     [
      #       -p=build,
      #       -header-filter="include/",
      #       --config-file=.clang-tidy,
      #     ]
      #   exclude: "test/.*" # gtest problems
  # CMake
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
      - id: cmake-lint
        args: [-disable=C0307]
  # General
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  # Python
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        files: ^pybind/
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        additional_dependencies: [toml]
        files: ^pybind/
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        files: ^pybind/
        args: ["--rcfile=pybind/pyproject.toml"]
