image: ubuntu:22.04

stages:
  - test

test:release:
  stage: test
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: on_success
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+/
      when: on_success
    - if: $CI_COMMIT_MESSAGE =~ /.*WIP.*/
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /.*(CI-TEST).*/
      when: on_success
  tags:
    - docker
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -qq
    - apt-get install -y gcc g++ cmake make git
    - apt-get install -y python3-dev python3-venv
    - apt-get install -y libopenmpi-dev libhdf5-openmpi-dev h5utils
    - apt-get install -y freeglut3-dev
    - apt-get install -y clang-format cpplint cppcheck
    - CI/run-all.sh
