
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, development, TestCI ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Testing:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update -qq
          sudo apt-get install -y gcc g++ clang-format-10 cmake make git
          sudo apt-get install -y python3-dev python3-venv
          sudo apt-get install -y libopenmpi-dev libhdf5-openmpi-dev h5utils
          sudo apt-get install -y freeglut3-dev
          
      - name: run
        run: |
          docker/.docker_run.sh
