
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Testing:
    runs-on: ubuntu-20.04

    steps:
      - name: dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update -qq
          sudo apt-get install -y gcc-9 g++-9 clang-10 clang-format-10 cmake make git
          sudo apt-get install -y python3-dev python3-venv
          sudo apt-get install -y libopenmpi-dev libhdf5-openmpi-dev h5utils
          sudo apt-get install -y freeglut3-dev

      - name: testing
        run: |
          docker/.docker_run.sh
          sudo apt-get remove -y freeglut3-dev
          sudo apt-get autoremove -y
          make clean
          make BUILD=debug CC=gcc-9 CXX=g++-9 install
          make test
