name: CI

on:
  push:
    branches: [main, development, TestCI]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  Tests:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        config:
          - { run-opengl: true }
          - { run-opengl: false }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update -qq
          sudo apt-get install -y gcc g++ clang-format-10 cmake make git
          sudo apt-get install -y python3-dev python3-venv
          sudo apt-get install -y libopenmpi-dev libhdf5-openmpi-dev h5utils

      - name: openGL
        run: sudo apt-get install -y freeglut3-dev
        if: matrix.config.run-it

      - name: run
        run: |
          ./CI/run-all.sh
